# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_pet', models.CharField(choices=[(b'CAT', b'cat'), (b'DOG', b'dog'), (b'FISH', b'fish'), (b'BIRD', b'bird')], max_length=50)),
                ('birth_date', models.DateField()),
                ('neutered', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[(b'N', b'Not Applicable'), (b'F', b'Female'), (b'M', b'Male')], default=b'Not Applicable', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Owner'),
        ),
    ]
