# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
