# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_auto_20170111_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='adoption.Owner'),
        ),
    ]
